### ISSUE TITLE
Project Blurb

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/hidden_collections_registry#10]
In the footer, we need to add a blurb of information about what this registry is.

**Comment by nkferraiolo** [comment]
I've sent some draft text to Amy and Christa for this. I'll send it to you once they've approved it.

**Comment by nkferraiolo** [comment]
I sent them a draft yesterday. I should have it approved by tomorrow. I'll give them a nudge.

**Comment by nkferraiolo** [comment]
Here's some text for the blurb!

"The CLIR Hidden Collections registry is a discovery tool to highlight rare and unique library, archival, and museum collections. It features projects funded through CLIR’s Cataloging and Digitizing Hidden Special Collections and Archives programs as well as numerous other special collections throughout the U.S. and Canada. If you are interested in adding collections to the registry, email hiddencollections@clir.org."
