### ISSUE TITLE
Visually differentiate funded projects

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/hidden_collections_registry#14]
Add a way to visually communicate visually which projects have been funded.

**Comment by nkferraiolo** [comment]
If you send me a spreadsheet of everything that is in the registry now, I can add a column designating which projects have been funded by CLIR.

**Comment by waynegraham** [comment]
They're all in https://github.com/clirdlf/hidden_collections_registry/tree/master/lib/assets (the `.xlsx` versions)
