### ISSUE TITLE
Create a user friendly view of the data model

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/hidden_collections_registry#15]
Create a user friendly (e.g. not the `db/schema.rb`) version of the database schema to make additions to the user interface easier to identify.

**Comment by nkferraiolo** [comment]
Following, I will look at this and help think through mapping issues.

**Comment by waynegraham** [comment]
@nkferraiolo see https://github.com/clirdlf/hidden_collections_registry/blob/94e5cd9939b248fab129426b05ec1a8d31a69157/doc/erd.pdf
