### ISSUE TITLE
Data Quality Assurance

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/hidden_collections_registry#19]
Review datasets to ensure the data we have reflects what was promised to Mellon

**Comment by nkferraiolo** [comment]
I have now gone through all proposals submitted to Mellon and have pulled the text relevant to the registry. I've made tickets for anything that was promised that is not already included. I'll send you a follow-up note with everything that needs to be completed by the end of the week and what can wait until later. 

Here's the round up of registry references in our proposals and reports: https://docs.google.com/document/d/1XmNXvHKOGZQDSmghJzP17N1DzrFDzdf-ItjWRmzRrSU/edit
