### ISSUE TITLE
Add institutions and collaborating institutions 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#20]
An important field that currently does not display is institutions that have received the awards (i.e. the recipients). This can be called "Institution", "Lead Institution", or "Award Recipient."

We will also want to add another field for "Collaborating Institutions" or "Collaborating Partners." This will only be applicable to about 30% of entries.

**Comment by waynegraham** [comment]
The institution is printed in the view when present (see https://github.com/clirdlf/hidden_collections_registry/blob/master/app/views/projects/show.html.erb#L58-L65).

**Comment by waynegraham** [comment]
This will require database work on the server side before this fix is reflected.

**Comment by waynegraham** [comment]
This last patch only fixes primary institutions and does not include the `pi2_organization` and `pi3_organization` fields

**Comment by waynegraham** [comment]
My understanding of this request from our meeting was that each of the individuals of the contributing institutions would be listed under the contact.

**Comment by nkferraiolo** [comment]
We need both. It's critical that the collaborating institutions are listed for the funded projects since they are official grant recipients. Not all of them will be represented by the contacts and PIs.

**Comment by waynegraham** [comment]
Is this a different field, and if so, what is it in the different datasets?

**Comment by nkferraiolo** [comment]
It can either be listed as additional items under institution, or as a separate field called "partner institutions."

In the 2014-2016 datasets, this is under the field "Collaborating Institution." Note that for the 2015-2016 cycles, some of the funded projects will have multiple partners, which appear on different lines on the spreadsheet. This is not yet available for 2008-2013, but I can get this data to you.

**Comment by waynegraham** [comment]
Waiting on 2008-2013

**Comment by nkferraiolo** [comment]
Data has been shared. The field for the 2008-2013 files is also called "Collaborating Institution."
