### ISSUE TITLE
Funny characters in spreadsheets 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#27]
In the WizeHive exports, sometimes symbols appear incorrectly, for instance, quotation marks become: â€œ. 

Should I correct this manually on the data export spreadsheets and resend them to you?

**Comment by waynegraham** [comment]
I was just noticing in the exports that there are UTF-8 errors. I suspect the `â€œ` is an en-dash and there is an issue in the encoding table. I can replace these in the file programmatically, but if you could verify that this is the character in the web interface I can write something to take care of that.
