### ISSUE TITLE
Remove year for unfunded projects 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#31]
Can we remove the Year Awarded field for all projects that weren't funded?

**Comment by waynegraham** [comment]
That's a bit more difficult; is there a better label we could use? Like "Grant Cycle" or something?

**Comment by nkferraiolo** [comment]
Oh no! I think politically, it would be tricky to leave that in because it would imply that they've applied for a grant before, which we don't want to do. It also doesn't make sense for people who want to add their information through the form I'll be creating. 

Let me try to talk to Christa about how important this is tomorrow. My hunch is that it is really important not to display the year for the unfunded projects, but she may have a good reason why we'd want to leave it in.

**Comment by waynegraham** [comment]
Each "funded" project will be clearly noted with a big green "Funded" label (see https://hcregistry.herokuapp.com/projects/23080989).

**Comment by waynegraham** [comment]
Change it to **Year Submitted**
