### ISSUE TITLE
Add field for "Collection/Project URL(s)"

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#38]
Eventually, we'll need to add a field for Collection/Project URL(s) for the funded projects. There should be the option for multiple URLs. The Program Administrator can add these in 2018. This will help people find the collections, which is what we promise to do. 

If possible, it would be great to have this field display only if there is data entered into it.

**Comment by nkferraiolo** [comment]
We're going to promise this capability to Mellon in our report, but we won't need it until 2018, when the Program Administrator has a chance to populate it.

**Comment by waynegraham** [comment]
There are two fields already for this: `project_url` and `repository_url`.

**Comment by nkferraiolo** [comment]
Awesome! So then we'll hold off until the PA gets here so she can populate them. After she gets settled, we should schedule a meeting so she knows how to do this.
