### ISSUE TITLE
Sharing registry records with other online catalogs 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#40]
Going through our past proposals, this is something that we promised Mellon repeatedly in the early days. It would be worth checking with Christa about whether they ever did this, if it is still necessary, and how we might approach this moving forward. This IMO is a lower priority item. 

This could perhaps be a good opportunity to get our data into this project: http://libraries.foundationcenter.org/.

**Comment by nkferraiolo** [comment]
Not at all urgent.

**Comment by waynegraham** [comment]
Can we just give them the dataset that we used to create the interface? The amount of effort it would take to fully implement an API layer to share data is significant.

**Comment by nkferraiolo** [comment]
I think that should be fine. This might not even be necessary, depending on what Christa and Jenna did before I was hired. I just wanted to flag it so we didn't forget. I've taken you off this task for the time being.

**Comment by waynegraham** [comment]
I'm looking at this again, and looking a bit at what the Foundation Center has. Unfortunately they do not provide much info on how organizations can contribute data. However, if they do find that the information is valuable for their project, it is available in [lib/assets](https://github.com/clirdlf/hidden_collections_registry/tree/master/lib/assets).
