### ISSUE TITLE
Linked formats

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#41]
When you click on a format type in the registry, it brings up only one or two other examples, instead of all the projects with that format. Is there a reason for this? For instance, if I click on "Manuscript", it only brings up one entry.

**Comment by nkferraiolo** [comment]
Would be awesome to have this by 9/22, but this can be pushed back if it's unrealistic.

**Comment by waynegraham** [comment]
I _believe_ what is going on has to do with how the data is getting inserted in to the database verses how it's displayed. To the database `Text` is different than `text`, so when the search is executed, there's not a check to standardize the case. Working on a fix.
