### ISSUE TITLE
"Institution type" field 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#42]
This is something that is useful to us and the Mellon Foundation for assessment purposes. However, there are other ways we can get this information so this is low priority and may not be necessary.

**Comment by nkferraiolo** [comment]
Not at all urgent

**Comment by waynegraham** [comment]
I'd like to make a differentiation between internally useful and what needs to be publicly displayed. Since this app is not intended to be an analytical tool, I'm not convinced this is a particularly useful feature for end uses.

**Comment by nkferraiolo** [comment]
That's fine.
