### ISSUE TITLE
Amount awarded for funded projects 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#44]
It would be GREAT to have a field for "amount awarded" or something like that for the funded projects. We already have this data, would it be possible to add a field but only have it display for funded projects? This is something that would be good to have in place in 2017.

**Comment by nkferraiolo** [comment]
It would be awesome to have this by 9/22. If not, we should have it in time for the 2018 cycle and new website launch. We will need this if the registry is to replace the Funded Projects page (which it turns out we told Mellon we'd do).

**Comment by waynegraham** [comment]
What are the fields in the CSVs that contain this information?

**Comment by nkferraiolo** [comment]
We don't have it for the 2008-2013 grantees, but I can get this information to you soon. 

For the 2014-2016 grantees, the field is called "Amount Requested."

**Comment by waynegraham** [comment]
Waiting on 2008-13 data edits

**Comment by nkferraiolo** [comment]
Data has been shared. The field name for this is also "Amount Requested."
