### ISSUE TITLE
To complete by 9/22/17

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#46]
The most important tickets to complete so that we can do the soft launch are: 
**#34** ("Program type" for unfunded projects), **#35** (Material Range), **#36** (Collaborating institutions), and **#47** (Public URL for registry). If you can get these done, we'll be ready to go in time for our final proposal submission. 

If by some miracle, you have additional time this week the next highest priorities are #41 (Linked formats), and #44 (Amount awarded for funded projects. If you don't have time to do these this week, it's fine if these are done sometime later in 2017.

**Comment by waynegraham** [comment]
These have been prioritized in Waffle
