### ISSUE TITLE
Public URL for registry 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#47]
We need to be able to link to the live URL in our final report to Mellon. I would be fine with keeping the same URL we have for the current registry. If you have other recommendations, I'm sure I'd be fine with that too. If need be, we can move it later and have it redirect. 

https://www.clir.org/hiddencollections/registry

**Comment by nkferraiolo** [comment]
We need this by 9/22.

**Comment by waynegraham** [comment]
What do you want the URL to be?

**Comment by nkferraiolo** [comment]
Can we just keep the same URL? I'm fine with the current one.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by waynegraham** [comment]
No, we can't mount an external app on a different server. We need a different URI to point users to. It think registry.clir.org is good enough (unless there's something that speaks to you more).

**Comment by nkferraiolo** [comment]
That works!! I like registry.clir.org!

**Comment by waynegraham** [comment]
Finished

**Comment by nkferraiolo** [comment]
Thank you!!!
