### ISSUE TITLE
Figure out how to deal with funny characters 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#48]
Wayne, what advice to you have for dealing with funny characters in the spreadsheet, for instance accented letters that make words look like this: Caffé Lena --> CaffÃ¨ Lena.

Is there a way we can automatically adjust these, or should I manually change them in the spreadsheets? Making the changes manually is no problem, but I want to make sure they show up in the registry after they're made.

**Comment by nkferraiolo** [comment]
I don't think we need this for the soft launch.

**Comment by waynegraham** [comment]
what field and dataset is this in? This is a UTF issue, but I have a string cleaning method to replace these (but will need to add `é`)

**Comment by waynegraham** [comment]
Actually, can I get a link to the record?

**Comment by nkferraiolo** [comment]
Yes! http://registry.clir.org/projects/1024

There are several with formatting issues like this, particularly in the descriptions.

**Comment by waynegraham** [comment]
These are data issues in the original dataset; need to process them out before they get in to the database. Unfortunately this will be a bit of cat-and-mouse as I'm not sure what Excel did to the data...

**Comment by nkferraiolo** [comment]
This is actually something that WizeHive did! There is no way to export reports from it without these errors. Let me know what I need to do to help make these changes. I can make them manually if need be.

**Comment by waynegraham** [comment]
😡
