### ISSUE TITLE
Formats for 2014-2016

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#49]
For some reason only one type of format is displaying for the projects between 2014-2016. Do you know why that is? What field are we pulling from for this information? Would another field such as "Type of Materials" be better because it includes all of the options?

**Comment by waynegraham** [comment]
The logic for updating records isn't working quite right for all the formats. This will take some time to sort out...

**Comment by waynegraham** [comment]
Closed in 8bf8c8d9bfdf3cdd04e3608486eae7d9eed43f50
