### ISSUE TITLE
Get rid of "what is this?" header above blurb

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#51]
I don't think it's necessary. The blurb speaks for itself. 

Though the blurb text could be a little bigger! :)

**Comment by waynegraham** [comment]
This should have a header because of how it will get crawled by Google, Bing, etc...

Is 16px "a little bigger" enough?

**Comment by nkferraiolo** [comment]
Oh OK, that makes sense. Would making the header "Hidden Collections Registry" work, or is that too redundant? I think 16px should work.
