### ISSUE TITLE
Add institution and collaborating institutions to thumbnail 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#52]
This is something we'll want visible on the main page for each funded project year if the registry is to replace our current funded projects page (see: https://www.clir.org/hiddencollections/awards), which is the hope! 

Note: we don't need this until the new website launches.

**Comment by waynegraham** [comment]
I don't understand what you're wanting here...

**Comment by nkferraiolo** [comment]
When search results are displayed, you see the title, image, and the beginning of the description. Is it also possible to display the lead institution in the summary view? 

This is not urgent.
