### ISSUE TITLE
When searching, clarify results

### ISSUE THREAD

**Issue by alucko** [clirdlf/hidden_collections_registry#57]
When a search is conducted, can we show the facet in the phrase (e.g. "289 audio entries")

**Comment by waynegraham** [comment]
So we're not using facets, so this information unfortunately isn't available. These are "tags" really, and a collection can have multiple formats. This search index uses a full text engine ([pg_search](https://github.com/Casecommons/pg_search)) to perform searches, but there's just no way to classify the type of results that are returned.
