### ISSUE TITLE
Add 2016 Thumbnail Images

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/hidden_collections_registry#69]
Need to walk team through creating and optimizing thumbnails.

We need to go over [Generating Thumbnails](https://github.com/clirdlf/hidden_collections_registry/blob/master/doc/thumbnails.md) and update for what doesn't make sense.

**Comment by waynegraham** [comment]
See 625ce24c0db780f53a2c381e9d44e6b20bb2d050

**Comment by joybanks** [comment]
I've reviewed the language and added a couple comments. The updates did clarify some things. Do we feel that an additional section(s) is needed for new thumbnails moving forward or modifying thumbnails after they've been uploaded? It seems like some of the steps may be a bit different.

**Comment by waynegraham** [comment]
Adding new thumbnails _should_ be covered by that doc. "Updating" _should_ just be overwriting the thumb. Feel free to expand this though.
