### ISSUE TITLE
Missing Data Since Search Interface Features Introduced

### ISSUE THREAD

**Issue by christawilliford** [clirdlf/hidden_collections_registry#74]
### Expected Behavior
Want to see all current data in the registry, 2008-2017.

### Actual Behavior
All the data in this subdirectory:
hidden_collections_registry/lib/program_data/digitizing_hidden_collections/

Is now missing from the Registry, since the faceted search features were introduced this week. When the Registry data was repopulated, was this subdirectory missed?

### Steps to reproduce the behavior
Just go to registry.clir.org. Note that all data from 2014-2016 is missing, and the 2017 data only includes the 7 projects for Recordings at Risk.

**Comment by waynegraham** [comment]
Regression on 00e6139f7cfdd47f4fb635c8fb9ca493a9c6b5ca

**Comment by waynegraham** [comment]
This is actually an indexing issue not related to the `feature/interface_update` branch. This **appears** to be related to the "fix" for materials.

**Comment by christawilliford** [comment]
Sorry for the mistake. Let me know if I posted the issue in the wrong or an unhelpful way. Still learning here.
